# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(upload_to=b'media/')),
                ('ordered_by', models.CharField(max_length=20)),
            ],
        ),
    ]
